import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'cdn.sanity.io' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
  },
  async redirects() {
    return [
      // Summerlin villages — plain name → prefixed slug
      { source: '/the-ridges', destination: '/summerlin-the-ridges', permanent: true },
      { source: '/the-ridges/', destination: '/summerlin-the-ridges', permanent: true },
      { source: '/the-arbors', destination: '/summerlin-the-arbors', permanent: true },
      { source: '/the-arbors/', destination: '/summerlin-the-arbors', permanent: true },
      { source: '/the-canyons', destination: '/summerlin-the-canyons', permanent: true },
      { source: '/the-canyons/', destination: '/summerlin-the-canyons', permanent: true },
      { source: '/the-hills', destination: '/summerlin-the-hills', permanent: true },
      { source: '/the-hills/', destination: '/summerlin-the-hills', permanent: true },
      { source: '/the-hills-south', destination: '/summerlin-the-hills-south', permanent: true },
      { source: '/the-hills-south/', destination: '/summerlin-the-hills-south', permanent: true },
      { source: '/the-cliffs', destination: '/summerlin-the-cliffs', permanent: true },
      { source: '/the-cliffs/', destination: '/summerlin-the-cliffs', permanent: true },
      { source: '/the-crossing', destination: '/summerlin-the-crossing', permanent: true },
      { source: '/the-crossing/', destination: '/summerlin-the-crossing', permanent: true },
      { source: '/the-gardens', destination: '/summerlin-the-gardens', permanent: true },
      { source: '/the-gardens/', destination: '/summerlin-the-gardens', permanent: true },
      { source: '/the-mesa', destination: '/summerlin-the-mesa', permanent: true },
      { source: '/the-mesa/', destination: '/summerlin-the-mesa', permanent: true },
      { source: '/the-pueblo', destination: '/summerlin-the-pueblo', permanent: true },
      { source: '/the-pueblo/', destination: '/summerlin-the-pueblo', permanent: true },
      { source: '/the-trails', destination: '/summerlin-the-trails', permanent: true },
      { source: '/the-trails/', destination: '/summerlin-the-trails', permanent: true },
      { source: '/the-vistas', destination: '/summerlin-the-vistas', permanent: true },
      { source: '/the-vistas/', destination: '/summerlin-the-vistas', permanent: true },
      { source: '/the-willows', destination: '/summerlin-the-willows', permanent: true },
      { source: '/the-willows/', destination: '/summerlin-the-willows', permanent: true },
      { source: '/grand-park', destination: '/summerlin-grand-park', permanent: true },
      { source: '/grand-park/', destination: '/summerlin-grand-park', permanent: true },
      { source: '/stonebridge', destination: '/summerlin-stonebridge', permanent: true },
      { source: '/stonebridge/', destination: '/summerlin-stonebridge', permanent: true },
      { source: '/siena', destination: '/summerlin-siena', permanent: true },
      { source: '/siena/', destination: '/summerlin-siena', permanent: true },
      { source: '/la-madre-peaks', destination: '/summerlin-la-madre-peaks', permanent: true },
      { source: '/la-madre-peaks/', destination: '/summerlin-la-madre-peaks', permanent: true },
      { source: '/ridgebrook', destination: '/summerlin-ridgebrook', permanent: true },
      { source: '/ridgebrook/', destination: '/summerlin-ridgebrook', permanent: true },
      { source: '/kestrel', destination: '/summerlin-kestrel', permanent: true },
      { source: '/kestrel/', destination: '/summerlin-kestrel', permanent: true },
      { source: '/redpoint', destination: '/summerlin-redpoint', permanent: true },
      { source: '/redpoint/', destination: '/summerlin-redpoint', permanent: true },
      { source: '/discovery', destination: '/summerlin-discovery', permanent: true },
      { source: '/discovery/', destination: '/summerlin-discovery', permanent: true },
      { source: '/south-square', destination: '/summerlin-south-square', permanent: true },
      { source: '/south-square/', destination: '/summerlin-south-square', permanent: true },
      { source: '/summerlin-centre', destination: '/summerlin-centre', permanent: true },
      // Common misspellings and alternative slugs
      { source: '/el-dorado', destination: '/eldorado', permanent: true },
      { source: '/el-dorado/', destination: '/eldorado', permanent: true },
      { source: '/waldorf-astoria', destination: '/waldorf-astoria-las-vegas', permanent: true },
      { source: '/waldorf-astoria/', destination: '/waldorf-astoria-las-vegas', permanent: true },
      { source: '/waldorf', destination: '/waldorf-astoria-las-vegas', permanent: true },
      { source: '/waldorf/', destination: '/waldorf-astoria-las-vegas', permanent: true },
      { source: '/four-seasons', destination: '/four-seasons-private-residences', permanent: true },
      { source: '/four-seasons/', destination: '/four-seasons-private-residences', permanent: true },
      { source: '/canyon-gate-cc', destination: '/canyon-gate-country-club', permanent: true },
      { source: '/canyon-gate-cc/', destination: '/canyon-gate-country-club', permanent: true },
      { source: '/macdonald-ranch-sun-city', destination: '/sun-city-macdonald-ranch', permanent: true },
      { source: '/macdonald-ranch-sun-city/', destination: '/sun-city-macdonald-ranch', permanent: true },
      { source: '/red-rock-cc', destination: '/red-rock-country-club', permanent: true },
      { source: '/red-rock-cc/', destination: '/red-rock-country-club', permanent: true },
      { source: '/rrcc', destination: '/red-rock-country-club', permanent: true },
      { source: '/rrcc/', destination: '/red-rock-country-club', permanent: true },
      // Lifestyle page aliases
      { source: '/guard-gated', destination: '/guard-gated-communities', permanent: true },
      { source: '/guard-gated/', destination: '/guard-gated-communities', permanent: true },
      { source: '/55-plus', destination: '/55-plus-communities', permanent: true },
      { source: '/55-plus/', destination: '/55-plus-communities', permanent: true },
      { source: '/active-adult', destination: '/55-plus-communities', permanent: true },
      { source: '/active-adult/', destination: '/55-plus-communities', permanent: true },
      { source: '/luxury', destination: '/luxury-communities', permanent: true },
      { source: '/luxury/', destination: '/luxury-communities', permanent: true },
      { source: '/high-rise', destination: '/high-rise-condos', permanent: true },
      { source: '/high-rise/', destination: '/high-rise-condos', permanent: true },
      { source: '/high-rises', destination: '/high-rise-condos', permanent: true },
      { source: '/high-rises/', destination: '/high-rise-condos', permanent: true },
      { source: '/new-construction-homes', destination: '/new-construction', permanent: true },
      { source: '/new-construction-homes/', destination: '/new-construction', permanent: true },
      { source: '/golf', destination: '/golf-communities', permanent: true },
      { source: '/golf/', destination: '/golf-communities', permanent: true },
      { source: '/historic-neighborhoods', destination: '/vintage-historic-neighborhoods', permanent: true },
      { source: '/historic-neighborhoods/', destination: '/vintage-historic-neighborhoods', permanent: true },
      { source: '/vintage-historic', destination: '/vintage-historic-neighborhoods', permanent: true },
      { source: '/vintage-historic/', destination: '/vintage-historic-neighborhoods', permanent: true },
      // Duplicate content redirects
      { source: '/canyon-gate-country-club', destination: '/canyon-gate', permanent: true },
      { source: '/canyon-gate-country-club/', destination: '/canyon-gate', permanent: true },
    ]
  },
}

export default nextConfig
