import type { Metadata } from 'next'
import LifestyleCollectionPage from '@/components/LifestyleCollectionPage'

export const metadata: Metadata = {
  title: '55+ Active Adult Communities in Las Vegas | Nevada Real Estate Group',
  alternates: { canonical: 'https://www.lasvegashomesearchexperts.com/55-plus-communities' },
  description: 'Explore 15+ active adult 55+ communities in Las Vegas and Henderson. Sun City Summerlin, Sun City Anthem, Solera, Trilogy. Resort-style living from $300K. Nevada Real Estate Group.',
}

export default function FiftyPlusPage() {
  return (
    <LifestyleCollectionPage
      title="55+ Active Adult Communities in Las Vegas"
      description="Las Vegas is one of the top retirement destinations in the country, and the metro area offers a wide range of 55+ active adult communities with resort-style amenities, golf courses, recreation centers, and organized social programs designed for active retirees."
      filterFn={(c) => {
        const type = c.type?.toLowerCase() || ''
        return type.includes('55+') || type.includes('active adult')
      }}
      slug="55-plus-communities" seoLabel="55+ Communities"
      editorial={[
        "Active adult communities in the Las Vegas Valley operate under the Housing for Older Persons Act (HOPA), which requires that at least 80 percent of occupied units have one resident aged 55 or older. The remaining 20 percent of units may be occupied by residents under 55, though individual community CC&Rs often impose stricter requirements. The Las Vegas metro area contains more than 15 age-restricted communities encompassing over 25,000 homes, making it one of the largest concentrations of 55+ housing in the western United States.",
        "Sun City Summerlin, built by Del Webb between 1989 and 2002, is the largest 55+ community in Nevada with 7,779 homes across four villages — Highland Falls, Palm Valley, Eagle Crest, and Sun City proper. Residents have access to four recreation centers totaling over 100,000 square feet, three golf courses (Highland Falls, Palm Valley, and Eagle Crest), and more than 80 chartered clubs and organizations. Sun City Anthem in Henderson contains 7,219 homes built by Del Webb between 1998 and 2008, featuring two championship golf courses (Anthem and Revere at Anthem), a 47,000-square-foot recreation center called Anthem Center, and a second 20,000-square-foot facility called Liberty Center. Homes in both communities range from $300,000 to $900,000 depending on size, lot, and upgrades.",
        "Smaller 55+ communities offer different price points and lifestyles. Solera at Anthem by Del Webb provides 1,700 homes priced from $350,000 to $600,000 with a single recreation center and more intimate social atmosphere. Trilogy by Shea Homes in Summerlin delivers a luxury active-adult product with homes from $500,000 to $1.3 million, resort-style pools, and a dedicated clubhouse. Regency by Toll Brothers at Summerlin and Regency at Providence in northwest Las Vegas offer newer construction with contemporary floor plans ranging from $450,000 to $800,000. HOA fees across these communities range from $150 to $450 per month and typically cover exterior landscape maintenance, recreation center access, and community security.",
        "Nevada Real Estate Group agents guide 55+ buyers through the age-verification process, community-specific CC&Rs, and the important differences between Del Webb communities and independent-builder developments. Nevada has no state income tax, which combined with a property tax cap that limits annual increases to 3 percent for primary residences makes the Las Vegas Valley especially attractive for retirees on fixed incomes."
      ]}
      faqs={[
        { q: "What are the age requirements for 55+ communities in Las Vegas?", a: "Under the federal Housing for Older Persons Act (HOPA), at least 80 percent of occupied units must have one resident aged 55 or older. Some Las Vegas 55+ communities enforce stricter rules — Sun City Summerlin requires the primary occupant to be 55+ and no permanent residents under 19. Each community publishes its own CC&Rs with specific age-related occupancy rules." },
        { q: "Can grandchildren live in a 55+ community?", a: "Most Las Vegas 55+ communities allow grandchildren to visit but restrict permanent residency for minors. Sun City Summerlin and Sun City Anthem both prohibit permanent residents under 19. Some communities permit minors to reside for limited periods, typically 30 to 90 days per year, but these policies vary. Buyers should review the specific CC&Rs before purchasing." },
        { q: "How much are HOA fees in Las Vegas 55+ communities?", a: "Monthly HOA fees in Las Vegas 55+ communities range from approximately $150 at older communities like Sun City Summerlin to $450 or more at newer luxury communities like Trilogy by Shea Homes. These fees typically cover exterior landscape maintenance, recreation center access, community pools, fitness facilities, and organized social programming. Sun City Anthem HOA fees average around $200–$250 per month." },
        { q: "Do 55+ homes in Las Vegas hold their resale value?", a: "Yes. 55+ communities in Las Vegas have demonstrated consistent demand due to ongoing retirement migration from California, the Pacific Northwest, and the Midwest. Sun City Summerlin homes that sold for $180,000–$250,000 in the early 2000s now trade between $350,000 and $700,000. The limited supply of age-restricted homes within established communities supports pricing stability, and the resort-style amenities are already built and paid for." },
        { q: "What social activities are available in Las Vegas 55+ communities?", a: "Sun City Summerlin offers over 80 chartered clubs including pickleball, tennis, woodworking, ceramics, hiking, cycling, poker, dance, and book clubs. Sun City Anthem operates more than 100 clubs and interest groups. Both communities host weekly social events, holiday celebrations, and organized day trips. Smaller communities like Solera at Anthem and Regency at Summerlin offer scaled-down but active social calendars through their recreation centers." },
        { q: "How close are 55+ communities to healthcare facilities?", a: "Sun City Summerlin is located within 5 miles of Summerlin Hospital Medical Center and 10 miles of Centennial Hills Hospital. Sun City Anthem in Henderson is within 6 miles of Henderson Hospital and 10 miles of St. Rose Dominican Hospital — Siena Campus. Both communities are within 20 minutes of the Las Vegas Medical District, which houses UMC Trauma Center, Valley Hospital, and multiple specialty clinics." },
        { q: "Are pets allowed in Las Vegas 55+ communities?", a: "Most Las Vegas 55+ communities allow pets with restrictions. Sun City Summerlin permits up to two domestic pets per household with breed and weight limits specified in the CC&Rs. Sun City Anthem allows dogs and cats with a two-pet limit and requires pets to be leashed in common areas. Some communities restrict certain breeds. Buyers with pets should confirm specific policies before purchasing." },
        { q: "Can you rent out a home in a 55+ community?", a: "Rental policies vary by community. Sun City Summerlin allows rentals with a minimum 12-month lease and requires the tenant to meet age requirements. Sun City Anthem permits rentals with board approval and a minimum 6-month lease term. Some newer communities like Trilogy restrict rentals during the first year of ownership. All tenants must comply with the community's age restrictions under HOPA guidelines." },
      ]}
    />
  )
}
