import type { Metadata } from 'next'
import LifestyleCollectionPage from '@/components/LifestyleCollectionPage'

export const metadata: Metadata = {
  title: 'Vintage & Historic Neighborhoods in Las Vegas | Nevada Real Estate Group',
  alternates: { canonical: 'https://www.lasvegashomesearchexperts.com/vintage-historic-neighborhoods' },
  description: 'Explore Las Vegas vintage and historic neighborhoods. Scotch 80s, Rancho Circle, Las Vegas Country Club, Old Town Henderson. Character homes with large lots from $300K to $8M+.',
}

export default function VintagePage() {
  return (
    <LifestyleCollectionPage
      title="Vintage & Historic Neighborhoods in Las Vegas"
      description="Before the master-planned communities, Las Vegas had character neighborhoods with mature trees, oversized lots, and architectural diversity. These vintage and historic areas offer a lifestyle that new construction cannot replicate — walkable streets, established character, and proximity to the urban core."
      filterFn={(c) => {
        const slugs = ['scotch-80s', 'rancho-circle', 'rancho-bel-air', 'rancho-manor', 'las-vegas-country-club', 'henderson-old-town', 'las-vegas-arts-district', 'las-vegas-charleston-heights', 'las-vegas-meadows-village', 'las-vegas-chinatown', 'downtown-las-vegas']
        const type = c.type?.toLowerCase() || ''
        return slugs.includes(c.slug) || type.includes('vintage') || type.includes('historic')
      }}
      slug="vintage-historic-neighborhoods" seoLabel="Vintage & Historic Neighborhoods"
      editorial={[
        "The vintage neighborhoods of Las Vegas were built between the 1940s and 1970s, before master-planned communities became the dominant development model. The Scotch 80s — named for Section 8 of the original Las Vegas land survey — is the most recognized vintage neighborhood, featuring approximately 350 homes on half-acre to one-acre lots bounded by Rancho Drive, Alta Drive, Hinson Street, and Highland Drive. Homes in the Scotch 80s were originally built in the 1960s and 1970s in ranch and mid-century modern styles, and today trade between $800,000 and $5 million or more depending on lot size, condition, and whether the home has been renovated or rebuilt. Notable past residents include Las Vegas entertainment figures, casino executives, and business leaders who shaped the city's identity.",
        "Rancho Circle, located adjacent to the Scotch 80s but further west along Rancho Drive, contains approximately 90 estates on 2.5-acre lots within a guard-gated perimeter. Rancho Circle lots were originally developed in the 1950s, and the community remains one of the most exclusive addresses in Las Vegas with homes priced from $1 million to $8 million or more. The Las Vegas Country Club neighborhood, developed in 1967 around an 18-hole course designed by Ed Ault, features homes on lots ranging from 10,000 to 30,000 square feet with prices from $500,000 to $2.5 million. The course itself closed and reopened multiple times, and the surrounding homes reflect the mid-century architectural character of the era with flat roofs, clerestory windows, and open floor plans.",
        "Old Town Henderson, centered along Water Street between Lake Mead Parkway and Basic Road, represents Henderson's original residential core dating to the 1940s when the Basic Magnesium plant drew workers to the area. Homes in Old Town Henderson range from $250,000 to $600,000 and sit on lots of 6,000 to 12,000 square feet. The McNeil Estate area near Rancho Drive and Charleston Boulevard contains mid-century homes on quarter-acre to half-acre lots priced from $400,000 to $1.5 million, with increasing interest from buyers seeking renovation opportunities. The Las Vegas Arts District south of downtown has seen residential conversions of commercial buildings into live-work loft spaces, with prices from $200,000 to $700,000.",
        "Nevada Real Estate Group agents who specialize in vintage properties guide buyers through the unique considerations of purchasing older homes in Las Vegas — including the absence of HOA governance in most vintage neighborhoods, the potential for flexible zoning that allows accessory dwelling units or home-based businesses, the condition of aging infrastructure (plumbing, electrical, roofing), and the renovation economics of updating a 1960s home versus a teardown-and-rebuild on a premium lot. Clark County property tax assessments on vintage properties with large lots can be notably lower per square foot than comparable-sized new construction because the land valuation methodology considers the neighborhood's established character."
      ]}
      faqs={[
        { q: "How large are the lots in Las Vegas vintage neighborhoods?", a: "Lot sizes in Las Vegas vintage neighborhoods are substantially larger than modern subdivisions. Rancho Circle offers the largest residential lots in the metro area at 2.5 acres each. The Scotch 80s features half-acre to one-acre lots. Las Vegas Country Club lots range from 10,000 to 30,000 square feet. McNeil Estate area lots run quarter-acre to half-acre. By comparison, typical new construction lots in master-planned communities like Summerlin or Cadence range from 3,500 to 8,000 square feet." },
        { q: "Can you renovate or rebuild on a vintage lot in Las Vegas?", a: "Yes. Vintage neighborhoods in Las Vegas are governed by Clark County or City of Las Vegas zoning codes, and most lots are zoned R-1 (single-family residential) which permits renovation, expansion, and in many cases complete demolition and rebuild. The Scotch 80s has seen numerous teardown-and-rebuild projects where buyers purchase a 1960s ranch home for the land value and construct a new 5,000–8,000-square-foot custom home. Building permits for new construction on existing lots typically take 4–8 weeks to obtain through Clark County." },
        { q: "Do Las Vegas vintage neighborhoods have historic designation?", a: "Las Vegas has very limited formal historic preservation compared to older American cities. The city of Las Vegas maintains a Historic Preservation Commission, but few individual properties or districts carry formal historic designation. The Scotch 80s neighborhood was nominated for the National Register of Historic Places but the application was not completed. As a result, most vintage homes in Las Vegas can be demolished or significantly altered without historic review — which gives owners maximum flexibility for renovation but does not provide tax incentives available in designated historic districts." },
        { q: "What are property taxes like on large lots in vintage neighborhoods?", a: "Clark County assesses property at 35 percent of taxable value. In vintage neighborhoods, the land component of the assessment reflects the neighborhood's established character and location rather than speculative new-development pricing. A half-acre lot in the Scotch 80s with a 3,000-square-foot original home might carry an annual tax bill of $4,000–$8,000, while a comparable lot size in a new luxury community could be assessed at $8,000–$15,000 due to higher improvement values. Nevada's 3 percent annual tax cap on primary residences limits increases for long-term owners." },
        { q: "Is zoning more flexible in vintage neighborhoods?", a: "Generally yes. Many vintage lots in Las Vegas carry R-1 or R-E (residential estates) zoning that permits detached accessory structures including casitas and guesthouses. Some properties along major corridors like Rancho Drive and Charleston Boulevard carry commercial or mixed-use zoning that enables home-based businesses, professional offices, or multi-use configurations. The absence of HOA restrictions in most vintage neighborhoods means there are no architectural review committees, no exterior color restrictions, and no CC&R-imposed limitations beyond county or city code." },
        { q: "What should buyers watch for when purchasing a vintage home in Las Vegas?", a: "Key inspection concerns in Las Vegas vintage homes include cast-iron or galvanized steel plumbing (common in pre-1975 homes, which may need replacement with copper or PEX), original electrical panels with limited amperage (60–100 amp panels are common vs. 200 amp in modern homes), single-pane windows, aging flat roofs with built-up roofing materials, and HVAC systems that may not adequately cool homes during 115-degree summer temperatures. Foundation issues are uncommon due to the desert climate, but expansive soils in certain areas of the valley can cause settling over decades." },
        { q: "Are there HOAs in Las Vegas vintage neighborhoods?", a: "Most Las Vegas vintage neighborhoods do not have homeowners associations. The Scotch 80s, McNeil Estate area, Las Vegas Country Club neighborhood, and Old Town Henderson all operate without HOA governance. Rancho Circle is an exception — it maintains a guard gate and a small HOA assessment. The absence of HOAs means no monthly fees, no architectural restrictions, and no exterior maintenance standards, which appeals to buyers seeking autonomy but means the neighborhood's aesthetic consistency depends entirely on individual homeowner decisions." },
      ]}
    />
  )
}
